### ISSUE TITLE
Signing key management

### ISSUE THREAD

**Issue by jkhelil** [tektoncd/chains#1190]
### Feature request
Currently, Chains lacks robust key management features, which poses potential security risks. Chains controller does not verify the validity or revocation status of signing keys, also the controller starts without ensuring the presence and validity of the required keys.

- Chains controller should perform a startup check for the presence of required signing keys.
- Chains controller should Implement a validity check for the signing key at startup and eventually periodically during operation (not sure if the key is loaded once or on each operation)
- The controller should panic and fail to start if no valid signing key is present.

**Comment by wlynch** [comment]
Few things to consider here:

- We don't want to panic if a valid key is not present. One of the things the Chains controller does is add a finalizer to objects to make sure they cannot be deleted before the reconciler has a chance to see and attest it. Causing the reconciler to crash for invalid keys would mean we could miss events coming though.
- Not every signer has keys ahead of time that you could validate against. Remote KMS and Sigstore ephemeral signing do not have keys on disk to validate against ahead of signing. In the case of Remote KMS Chains may not have any access to the key material, and in the case of Sigstore the issued cert is validated during signing on admission to Rekor.
- Does it make sense for the Chains signer to do this kind of verification? The existence of a signature doesn't convey additional security on it's own. Verification policies and CRLs may differ from the server to the client, so there's no guarantee that any checks we add server side for checking revocation are correct/intended by the client.

**Comment by jkhelil** [comment]
Thank you @wlynch for the insightful feedback. Your points about different signing mechanisms, including remote KMS and Sigstore, are valid. Also the distinction between server-side and client-side checks is true.
I believe we should still address the critical scenario of key compromise. at least at documentation level.
- What happens if a signing key is compromised? chains controller will keep using it, until the admin deletes the secret (is that something acceptable)
- What are the implications for objects that have already been signed with a compromised key? theorcally we can no longer trust their provenance, what does that mean for an admin/user (is he able to identify the affected objects, what kind of actions he can take).

**Comment by wlynch** [comment]
> What happens if a signing key is compromised? chains controller will keep using it, until the admin deletes the secret (is that something acceptable)

This is probably okay? Even if the chains controller continues to use the key, the signatures should be treated as untrusted by verifiers. I don't think it can be chains responsibility to enforce policy on what keys are considered valid/invalid.

e.g. if a key was discovered to be compromised, but there was a period of time before this was discovered, even if you had a feature like this there already could be signatures floating around by the chains controller because the key was valid at the time of signing but was retroactively considered revoked/untrusted later on.

> What are the implications for objects that have already been signed with a compromised key? theorcally we can no longer trust their provenance, what does that mean for an admin/user (is he able to identify the affected objects, what kind of actions he can take).

Chains doesn't have a great story for re-attesting today, though you could probably do this by removing the control annotations Chains uses to track whether it has signed an object. It might be interesting if Chains had a "please re-attest this" CLI command, but this would only work if the run metadata was still present on the cluster.

In general, you would invalidate and remove any provenance/artifacts that match the compromised keys and possibly rebuild new versions. https://blog.sigstore.dev/dont-panic-a-playbook-for-handling-account-compromise-with-sigstore-ee299dca5144/ has a good summary of how to approach this, and using Sigstore's Rekor with Chains would make it much easier to locate the affected artifacts.

Totally open to clearer documentation on this! (though actual steps will probably vary depending on your PKI setup)
