### ISSUE TITLE
Sign other types of artifacts

### ISSUE THREAD

**Issue by priyawadhwa** [tektoncd/chains#124]
Right now we only sign TaskRuns and OCI Images, but it would be cool to give users a way to sign other types of results (binaries, files, whatever)

**Comment by mattmoor** [comment]
Two that immediately come to mind are PipelineRuns as well as Runs (for custom tasks cc @imjasonh).

It might also be prudent to better formalize the way image outputs are signed.  I was spitballing this with @dlorenc a week or so ago, but this would be another great application of duck typing task/pipeline[1] input/output shapes (as I was playing with in mattmoor/mink motivated by CLI DevX).

_[1] - From here on I'm going to say "task" when I really mean task, pipeline, or a user-defined custom task definition._

The general idea is that tooling (including some possible defined by Tekton upstream) would standardize around certain task signature "shapes".  Imagine if tasks with outputs named like `dev.tekton.imagedigest.*` (strawman) could be interpreted as being image digest outputs?

These duck types aren't semantically meaningful to tekton/pipeline itself (like say pipeline resources were), but enable an extensibility model that puts the burden of adhering to such conventions on consuming tools (e.g. `tkn`, dashboard, chains).

Another aspect of wanting standardization of certain conventions is that we can start to make the catalog adhere to them so that folks can get a really nice OOTB experience.

**Comment by lcarva** [comment]
[TEP-84](https://github.com/tektoncd/community/blob/main/teps/0084-endtoend-provenance-collection.md) is related to signing of PipelineRuns.

**Comment by bobcatfish** [comment]
I think this might be being covered by the TEP-0109 structured results work by @ywluogg ?

/reopen

**Comment by bobcatfish** [comment]
For anyone looking for this functionality, the place it is currently documented is https://github.com/tektoncd/chains/blob/main/docs/intoto.md#structured-result-type-hinting
