### ISSUE TITLE
Diagram overview of processes

### ISSUE THREAD

**Issue by mtcolman** [tektoncd/chains#283]
Hi, I was wondering whether a diagram showing an overview of how chains works would be useful to include in one of the READMEs? This is something I've had a go at putting together (it is based on the [getting started](https://github.com/tektoncd/chains/blob/main/docs/tutorials/getting-started-tutorial.md) and [signed provenance](https://github.com/tektoncd/chains/blob/main/docs/tutorials/signed-provenance-tutorial.md) tutorials).

![image](https://user-images.githubusercontent.com/33348891/141770504-e15ce62d-ed57-4360-bf1b-98b27c0cd4cf.png)

**Comment by priyawadhwa** [comment]
Hey @mtcolman thanks for making this, it's really cool 🎉 ! I think this could be useful linked in the signed provenance tutorial since it's a nice diagram of what that tutorial is doing 😄  I just have a couple suggestions:
- could you move things related to chains setup as the first couple setups? This would include step 5 (editing chains config) and step 6 (setting up cluster auth). that way the flow of reading what chains is actually doing won't get interrupted by setup.
- Rekor should be moved out of the cluster since it's running as a separate service

**Comment by mtcolman** [comment]
@priyawadhwa how about these?

---------------------

### Getting Started Tutorial
![image](https://user-images.githubusercontent.com/33348891/142262579-e32a02aa-ac1f-4f08-844e-9aa14980c07c.png)

---------------------

### Signed Provenance Tutorial
![image](https://user-images.githubusercontent.com/33348891/142262619-5fda2ba1-a9b5-4332-b039-39884ed1b82d.png)

---------------------

**Comment by priyawadhwa** [comment]
Hey @mtcolman thanks for updating the diagrams! Just a couple more thoughts and then we should be good:

Getting Started Tutorial:
- This tutorial builds the `gcr.io/foo/bar` image but never actually pushes it to a registry (that way we don't have to worry about setting auth and stuff like that). so maybe we remove the push to the remote registry, and just say that the image was built?


The diagram for the signed provenance tutorial looks great!

**Comment by mtcolman** [comment]
@priyawadhwa here you go, updated "Getting Started Tutorial" diagram:

![image](https://user-images.githubusercontent.com/33348891/144093191-d6d41884-592c-4667-be94-a48e3b26fc9f.png)

**Comment by priyawadhwa** [comment]
Amazing! If you have time to open a PR adding these to the tutorials I can get it merged in. I think this is gonna be really useful for people 😄

**Comment by mtcolman** [comment]
Closed by #294
