### ISSUE TITLE
SLSA v0.2 provenance implementation for materials.digest (if using git) doesn't line up with spec

### ISSUE THREAD

**Issue by mlieberman85** [tektoncd/chains#309]
materials.digest as implemented has a key for materials.revision but not for materials.digest which is in the spec.

> materials[*].digest object (DigestSet), optional
> Collection of cryptographic digests for the contents of this artifact.

One thing to not is there is currently some ambiguity in SLSA as to whether or not "commit id" counts as digest. https://github.com/slsa-framework/slsa/issues/214 -- However looking at a https git reference can be confusing without adding `git+` to the URI. Do other folks have any thoughts?

Similar to #306 and #307

See: https://github.com/slsa-framework/slsa/blob/main/docs/provenance/v0.2.md

**Comment by priyawadhwa** [comment]
Looks like there are two bugs here:
1. Instead of using the "revision" key we should be using "sha1" to indicate a commit, which is what the provenance in the the [github actions example](https://github.com/slsa-framework/slsa/blob/main/docs/provenance/v0.2.md#github-actions) does

```
  "configSource": {
    "entryPoint": "build.yaml:build",
    // The git repo that contains the build.yaml referenced in the entrypoint.
    "uri": "git+https://github.com/foo/bar.git",
    // The resolved git commit hash reflecting the version of the repo used
    // for this build.
    "digest": {"sha1": "abc..."}
  },
```

2. we need to add the `git+` prefix and `.git` suffix to the URI

**Comment by mlieberman85** [comment]
There is also: https://github.com/in-toto/attestation/issues/28 here. There is some discussion if some of this at the attestation spec level as well.
