### ISSUE TITLE
Verify the SCT coming back from Fulcio.

### ISSUE THREAD

**Issue by vaikas** [tektoncd/chains#326]
### Feature request
I think we should verify the SCT coming back from Fulcio to ensure we're not being bamboozled by it. So here:
https://github.com/tektoncd/chains/blob/main/pkg/chains/signing/x509/x509.go#L83

We call the fulcio.NewSigner, but I think we should consider calling the fulcioverifier version of it here:
https://github.com/sigstore/cosign/blob/main/cmd/cosign/cli/fulcio/fulcioverifier/fulcioverifier.go#L96

Which then in turn additionally verifies the SCT coming back here:
https://github.com/sigstore/cosign/blob/main/cmd/cosign/cli/fulcio/fulcioverifier/fulcioverifier.go#L103

My understanding is that it's not quite as simple as just importing this version due to some conflicting log imports from here:
https://github.com/sigstore/cosign/blob/main/cmd/cosign/cli/fulcio/fulcioverifier/fulcioverifier.go#L29

But, maybe it's just as simple as just swapping? :) Haven't had a chance to verify it yet, just jotting this down.

### Use case
It's important to verify that Fulcio actually added the Certificate to a CTLog and SCT is that proof, so it should be verified. Currently we don't (or I totes missed where we dot it).

**Comment by priyawadhwa** [comment]
Thanks for catching this, we definitely should be verifying the SCT!

Unfortunately it looks like just swapping might not work, seems like the dependency you pointed out (`"github.com/google/certificate-transparency-go/x509"`) depends on `glog` which Chains [can't depend on](https://github.com/tektoncd/chains/blob/main/cmd/controller/main_test.go#L23-L27) because of the "log_dir redefined flag error" 😞 

We could either try to remove the glog dependency from the `certificate-transparency-go` lib upstream, or try to rewrite the SCT verification in Chains. First option is probably better!

**Comment by haydentherapper** [comment]
We do verification in Cosign, and worked around the `glog` issue by copying in `ctutil` - https://github.com/sigstore/cosign/blob/7ba521444f9fcfdf2e1e5936c05834597674e6c9/cmd/cosign/cli/fulcio/fulcioverifier/ctutil/ctutil.go

See https://github.com/sigstore/cosign/blob/30bf1c09c6fde849245648ff294725d86094fe28/cmd/cosign/cli/fulcio/fulcioverifier/ctl/verify.go for the verification. It still pulls from `certificate-transparency-go`, but avoids pulling in anything with `glog`.

**Comment by wlynch** [comment]
We mirrored the policy-controller replace in https://github.com/tektoncd/chains/pull/514 so I don't think glog is a blocker anymore.

@haydentherapper Should we just upstream the SCT check to the Fulcio library? sigstore-go also works, but this feels fundamental enough that it might make sense in fulcio proper. 🤔

**Comment by haydentherapper** [comment]
Yea, I'd be fine with adding that into a fulcio package!
