### ISSUE TITLE
Proposal: Separate KSAs for different operations

### ISSUE THREAD

**Issue by chuangw6** [tektoncd/chains#455]
### Feature request

Currently, there is only one KSA named `tekton-chains-controller` under `tekton-chains` namespace for authentication in different operations such as signing (kms key access), and storage (storage backend access i.e. grafeas).

Would it be possible to have separate KSAs for these different operations?

### Use Case
Motivation behind this is to NOT force signing and storing operations to use the same SA (i.e. workload identity) for the sake of security reasons.

cc @wlynch @ykass

**Comment by wlynch** [comment]
To clarify, are you asking for:

1. Different instances of chains on the same cluster, each with their own identity/permissions (i.e. 1 per namespace)?
2. Separating out signing and storage writing into separate pods in the same namespace?

If 1, I'm all for it! There was some [recent discussion in Slack](https://tektoncd.slack.com/archives/C015FAQV290/p1653489698493779) that might be of interest here.

For 2, I'm not totally grokking why this would be better than the current setup, since there would be an implicit trust between the signer and the storage writer. Can you go into a bit more detail about what kind of attacks we are aiming to mitigate with this and how this would address them?

**Comment by priyawadhwa** [comment]
For 1, I think it should still be ok to have just the `tekton-chains-controller` KSA since it'll be per namespace.

I'd also like more clarity around (2) if that's the main goal!
