### ISSUE TITLE
Deprecate SLSA v0.1 format

### ISSUE THREAD

**Issue by wlynch** [tektoncd/chains#597]
### Feature request

TaskRun intoto provenance uses an older [SLSA v0.1](https://slsa.dev/provenance/v0.1) style which is missing a bunch of fields in the TaskRun spec (thanks @chitrangpatel for pointing this out!)

- workingDir
- volumeMounts
- imagePullPolicy
- securityContext
- onError
- ...

Currently, we have a few different types of intoto provenance:

- https://github.com/tektoncd/chains/blob/main/pkg/chains/provenance/provenance.go (SLSA v0.1)
- https://github.com/tektoncd/chains/blob/main/pkg/chains/formats/intotoite6/taskrun/buildconfig.go (hybrid of SLSA v0.1 and v0.2)
- https://pkg.go.dev/github.com/in-toto/in-toto-golang/in_toto/slsa_provenance/v0.2 (SLSA v0.2 - only used by PipelineRun)

Let's move everything over to SLSA v0.2 so we're including more data.

cc @lcarva

**Comment by wlynch** [comment]
Rough plan:

- [ ] Introduce a new `slsa0.1` option that preserves existing behavior - make `intoto` an alias for this type.
  - Remove one of the provenance / buildconfig types for `slsa0.1` to standardize.
  - Also probably add `slsa` alias for parity.
- [ ] Add new `slsa0.2` option that introduces new spec (likely based on the existing run type) - more details on spec to come (likely related https://github.com/tektoncd/community/pull/820)
- [ ] After next release - point existing `intoto` alias to `slsa0.1`

cc @chuangw6 - we were talking about a similar type alias before so lmk if this sounds good.

**Comment by chuangw6** [comment]
I think [taskrun level intoto provenance](https://github.com/tektoncd/chains/blob/ed0bd409eb1cb5a76ff5dbac6a21433b3240ad79/pkg/chains/formats/intotoite6/taskrun/taskrun.go#L29) is already following SLSA 0.2 spec. 

And SLSA 0.1 has been deprecated for a while, https://github.com/tektoncd/chains/blob/main/pkg/chains/provenance/provenance.go (SLSA v0.1) is not used/called anywhere in the code base so we might be able to delete it safely?

Did I misunderstand anything here? 🤔

**Comment by wlynch** [comment]
That's why it's a hybrid - it's SLSA 0.2 spec using SLSA 0.1 fields. 🙃

Important thing I care about is making sure we don't break anyone unexpectedly.

**Comment by chitrangpatel** [comment]
@chuangw6 and I just had a discussion regarding this. Summarizing here:
1. Current `intoto` format has the same predictate is SLSAv0.2. However, the information that goes into the several underlying fields like `buildConfig, invocation` are incomplete. **Meaning this is a flavour of `SLSAv0.2` predicate generated by chains**.
2. TEP https://github.com/tektoncd/community/pull/820 is trying to make that complete. This will be a new flavour of `SLSAv0.2` that chains generates. 

To preserve the current `intoto` format, we might have to alias it as `slsav0.2/chainsv1` (or something; you probably get the idea of what I mean) and the new format as `slsav0.2/chainsv2` instead of calling the current `intoto` format `slsav0.1` (because the predicate is very different from what we have now).

@chuangw6 anything I missed?

@wlynch let us know what you think.

**Comment by chuangw6** [comment]
> I'd simplify things a bit w.r.t. the versioning - i.e. slsa/v1, slsa/v2, ...
I don't think we strictly need to match our version numbers with SLSA

I feel this might become confusing in the long term  especially when slsa v1 is released. In that case, Chains needs to support the new slsa v1 provenance, but we still having an option like `slsa/v2`, which might be confusing XD

> we're unlikely going to support multiple versions of SLSA provenance in parallel outside the sliding deprecation window.

There was discussion around supporting both slsa v0.2 and future slsa v1.0 provenance https://github.com/tektoncd/chains/issues/477#issuecomment-1177751216. While we will deprecate slsa v0.2 at some point after v1 is released, I think we would need to support both for a long period of time.

**Comment by chitrangpatel** [comment]
I think we may also want to consider upgrades to chains:

For example, in the current case, we are currently upgrading slsav0.2 predicate to make it complete. 
That is a major change for which we want backwards compatibility (I think that's what this issue is trying to highlight). 


So in the future even if we move to slsav1.0, we will have upgrades to chains's implementation of it. Will we want backwards compatibility then as well to older implementations of slsav1.0 predicate? May be just for the sliding deprecation window?

I think this probably needs some more discussion.

**Comment by wlynch** [comment]
The way I'm looking at it is these would be versions of Chains SLSA provenance - whether they are backed by the same SLSA predicate version would still be encoded in the predicateType.

In general I wouldn't expect new changes to be backported for older versions - we'd either make backwards compatible changes for the latest version or rev a new version with breaking changes. Older versions would be kept around for compatibility and eventually phased out.

What I'd like to avoid is situations where you need to figure out "is `slsa0.2/v3` more recent than `slsav1/v1`"?

What I'd rather do is have a table where we say:

- slsa/v1 = SLSA v0.2 predicate
- slsa/v2 = SLSA v0.2 predicate with new field structure.
- slsa -> slsa/v3 = SLSA v1 predicate
- slsa/v4alpha1 = New predicate format we're working on but isn't ready yet

**Comment by chuangw6** [comment]
> The way I'm looking at it is these would be versions of Chains SLSA provenance
> What I'd rather do is have a table where we say:

Thanks for clarification. That makes sense.

**Comment by chitrangpatel** [comment]
Thanks @wlynch! That clarifies things a lot.
