### ISSUE TITLE
The predicate.buildType syntax not in compliance with SLSA v0.2

### ISSUE THREAD

**Issue by zregvart** [tektoncd/chains#612]
# Expected Behavior

The [predicate.buildType](https://slsa.dev/provenance/v0.2#buildType) in SLSA v0.2 is of type string with [TypeURI](https://github.com/in-toto/attestation/blob/main/spec/field_types.md#TypeURI) format, which is defined in [RFC 3986](https://tools.ietf.org/html/rfc3986).

# Actual Behavior

The current `predicate.buildType` is not a valid RFC 3986 URI because it's missing the [scheme component](https://www.rfc-editor.org/rfc/rfc3986#section-3.1).

# Steps to Reproduce the Problem

1. Create a Tekton TaskRun or a PipelineRun
2. Notice that the Chains controller generates the attestation JSON with predicate.buildType not in RFC 3986 syntax

# Additional Info

A common prefix, such as `https://` could be added to [TaskRun](https://github.com/tektoncd/chains/blob/9a47793b009bd576f53a777a810e3ffebe45f7a4/pkg/chains/formats/intotoite6/taskrun/taskrun.go#L41) or [PipelineRun](https://github.com/tektoncd/chains/blob/9a47793b009bd576f53a777a810e3ffebe45f7a4/pkg/chains/formats/intotoite6/pipelinerun/pipelinerun.go#L60) attestations.

**Comment by chuangw6** [comment]
Thanks @zregvart for filing this ticket. Concur with that. I think there are 2 changes we need to make. 

- to make sure the `buildType` field is fully in-spec with SLSA 0.2. 
@chitrangpatel may have more knowledge about this. Essentially, we might need to create documentations and the buildType is the uri pointing to the docs because based on the [slsa definition](https://slsa.dev/provenance/v0.2#buildType): buildType should be "URI indicating what type of build was performed. It determines the meaning of invocation, buildConfig and materials." . 

- I think we would also add a new configmap field to make the field is configurable.
Reasoning: The cloud builders that uses tekon as the infrastructure may need the field to point to their own flavoured documentations. Therefore, making it configurable would be beneficial to those users.

**Comment by wlynch** [comment]
The new `slsa/v2alpha1` provenance format that's currently WIP changes this to:

https://github.com/tektoncd/chains/blob/ad16eb4661d7634567e97aa1754ecd23c19b8626/pkg/chains/formats/slsa/v2/taskrun/taskrun.go#L58

Which should cover this. 

I know we've made changes to this before, but I'm a bit hesitant to make additional changes to the `slsa/v1` buildType after seeing the challenges that popped up after making a similar change in cosign - https://github.com/sigstore/cosign/pull/2737. We ended up having to walk it back because users were keying on the predicateType and broke downstream tools / policies.
