### ISSUE TITLE
Allowing the user to control the provenance format and contents

### ISSUE THREAD

**Issue by chitrangpatel** [tektoncd/chains#694]
## Feature request

This feature request is about making `Chains` more flexible in the formatting of the provenance it generates (e.g. allowing users of Chains to have control over what values go where in the generated provenance). 

### Use case
This will also allow Tekton service providers the ability to tune the provenance format for their customers and match their buildType. The same likely goes for developers that are extending Chains to their use case.

### Templating

We could consider `templating` the provenance (see below as a very rough and initial example):

```json
{
    "_type": "https://in-toto.io/Statement/v0.1",
    "predicateType": "https://slsa.dev/provenance/v0.2",
    "subject": [
        {{range .slsav2.Subject}}
        {
            "name": "{{.Name}}",
            "digest": {        
                "{{.ShaType}}": "{{.Digest}}"
            }
        }
        {{end}}
    ],
    "predicate": {
        "builder": {
            "id": "https://gcbv2"
        },
        "buildType": "https://gcbv2/workflows/TaskRun",
        "invocation": {
            "configSource": {{ TaskRunObject.Status.Provenance.ConfigSource }},
            "parameters": {{ slsav2.Parameters }},
            "environment": {
                    "tekton-chains": "v0.13",
                    "tekton-pipelines": "v0.44.0",
                    "gcb-resolver": "v0.1.0",
                    "tekton-feature-flags": {{ TaskRunObject.Status.Provenance.FeatureFlags }}
            }
        },
        "buildConfig": {},
        "metadata": {
            "buildStartedOn": "{{index .BuildStartTimes 0}}", 
            "buildFinishedOn": "{{index .BuildFinishedTimes 0}}",
            "completeness": {
                "parameters": false,            
                "environment": false,           
                "materials": false              
            },
            "reproducible": false           
        },
        "materials": [
            {{range .slsav2.URIDigest}}            
            {
                "uri": "{{.URI}}",              
                "digest": {
                    "{{.ShaType}}": "{{.Digest}}"   
                }
            },
            {{end}}
        ]
    }
}
```

**Comment by lcarva** [comment]
+1

The templating approach could also make it easier to document, and understand, which attributes from the underlying resource (TaskRun, PipelineRun) map to attributes in the provenance attestation.

**Comment by wlynch** [comment]
Thanks for putting this together! (sorry about the delay - out at a conference this week)

I like the idea of including runtime version metadata, and I think it would be a good idea to include it in the provenance that chains generates.

I have some concerns about templating though -

I'm worried that allowing arbitrary templating will introduce fragmentation. It would be hard to distinguish template variants from distinct provenance build types, which could make it harder for consumers to write policies that target particular variants and know what data is available.

The preprocessing required would also likely need to be fairly opinionated, e.g. in your example template variables are not pulled from the TaskRun data itself - they are targeting intoto/slsa and are making decisions on what is / isn't a subject, etc. I'm not sure this is substantially better than seeing how we can make the existing library functions easier to work with.
At worst, this could be used to let users forge provenance and have the chains controller sign it (e.g. if I use a template that sets predetermined data).

re setting custom build types / builder ids - I don't think we should allow allowing modifications to the build type, since this is a type hint about the provenance data we are attesting to in the build config. I'm generally in favor of allowing the builder ID to be configurable, but I'd prefer for this data to be observed from the Run status of the executed build (similar to how you're referencing feature flags from the Run status). /cc @chuangw6  and @r2wend2 who were involved in previous discussions related to this.

lmk if this makes sense. Happy to discuss more!

**Comment by chitrangpatel** [comment]
Thanks @wlynch! I agree, we do need some level of preprocessing that chains needs to do. 

I am thinking of this from [slsav1.0](https://slsa.dev/github-actions-workflow/v1). Now that there is `systemParameters` and `externalParameters`, what items belong in `systemParameters` vs `externalParameters` depends on the builder's configuration. 
eg.  a builder might choose to auto-populate some parameters for its customers and will want to insert them in `systemParamerters`. On the other hand, `chains` might treat them as `externalParameters`. Ultimately, its the builder (I think) that needs to provide the provenance for its users and so the builder's format of the provenance is what is important.
 Some level of templating will be beneficial here. I do agree that somethings need additional processing from what is contained in the taskrun/pipelinerun CRDs so we need to find a balance that works.

Happy to brainstorm this more at one of the upcoming WG meetings!

**Comment by wlynch** [comment]
For that example, I'd challenge why the builder needs to stuff everything in params. 😅 

If the generated param is something you would expect the user to set, then it would act just like any other param and should be included in `externalParameters`. If the generated param is something that shouldn't be set by the user and is something intrinsic to the builder environment, I'd argue that's not a param but rather closer to a [build context value](https://github.com/tektoncd/pipeline/blob/0b699455199cf1b80212ef1becade922883b0186/docs/variables.md?plain=1#L36-L39). 
I think it's a valid use case, but it might make more sense to make that distinction in the Pipeline API itself - e.g. add a `context` field to the Run status with any values provided by the build environment, then use that to populate `systemParameters`.

There's some prior art here with GitHub Actions [`context`](https://docs.github.com/en/actions/learn-github-actions/contexts) vs [`input`](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs) that we may be able to learn from.

**Comment by tbe** [comment]
This is still a required feature. For example, we would like to add [vuln attestations](https://github.com/sigstore/cosign/blob/main/specs/COSIGN_VULN_ATTESTATION_SPEC.md) to our final output. There seems to be no way in chains to support vuln scans in general. Allowing the user to template them, would allow for more complex scenarios.
